import os
from flask import Flask,flash,render_template,jsonify,redirect,request , url_for

UPLOAD_FOLDER = 'uploads/audios/'
ALLOWED_EXTENSIONS = {'wav'}

app = Flask(__name__)
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

@app.route("/output")
def predict():
    # write wave2vec inference code here. The audio file name is temp.wav
    transcript = "TEXT GENERATED BY ASR"
    return jsonify(transcript)

@app.route("/", methods=["GET","POST"])
def index():
    if request.method == "POST":
        if 'file' not in request.files:
            flash('No file part')
            return redirect(request.url)
        file = request.files['file']
        file.filename = request.form['fname']
        if file :
            file.save(os.path.join(app.config['UPLOAD_FOLDER'], "temp.wav"))
    return render_template('index.html'), 201

if __name__=='__main__':
    app.run(debug=True,port=8000)